---
title: "S151_created_master_vis"
author: "fk506.cni"
date: "2023-05-24"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
require(tidyverse)
require(openxlsx)
require(jsonlite)
require(officer)
require(ggpubr)
```


```{r}
outputdir <- "./figs/"
if(!dir.exists(outputdir)){
  dir.create(outputdir)
}

ggsave2_tri <- function(plot, wid = 9, hei=9){
  plot_name <- deparse(substitute(plot))
  
  #png
  file_name <- paste(outputdir,plot_name, ".png", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "png",width = wid, height = hei,dpi = 300,units = "cm")
  
  
  #pdf
  file_name <- paste(outputdir,plot_name, ".pdf", sep = "",collapse = "")
  # ggsave(filename = file_name,plot = plot,device = "pdf",width = wid, height = hei,dpi = 300,units = "cm")
  
  #pptx
  file_name <- paste(outputdir,plot_name, ".pptx", sep = "",collapse = "")
  plot_ed <- rvg::dml(ggobj = plot,width = wid, height = hei)
  
  doc <- read_pptx() %>%
    add_slide('Title and Content', 'Office Theme') %>%
    ph_with(value = "", location = ph_location_type(type = "title")) %>%
    ph_with(value = plot_ed, location = ph_location(type = "body",width = cm2inch(wid), height = cm2inch(hei),left = 2, top = 2))
  doc %>%
    print(target = file_name)
  
}



inch2cm <- function(x){
  return(x/0.39370)
}
cm2inch <- function(x){
  return(0.39370*x)
}

p2cm <- function(x){
  return(as.integer(0.008466666666666667 * x))
}

cm2p <- function(x){
  return(as.integer(118.11023622047244 *x))
}

sv2ggkm <- function(svfit){
  p <- ggsurvplot(fit = svfit, data = df,
                risk.table.title = "risk.table.title", risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE, fontsize = 5,
           risk.table = TRUE, tables.theme = theme_pubr(), ggtheme = theme_pubr())
  p_km <- p$plot
  p_tb <- p$table
  p2 <- cowplot::plot_grid(p_km, p_tb, ncol = 1,align = "v", rel_heights = c(3,1))
  grid::grid.draw(p2)
  return(p2)
}
```

```{r}
# f_iy_mst_whole <- "../X102_kikin_master_for_anal/ndb_master_creation/appendix/dfmeta_20230427_133748_521448_mod.xlsx"
# f_iy_mst_whole <- "../X102_kikin_master_for_anal/ndb_master_creation/appendix/dfmeta_iy_20230606_124628_792271.xlsx"

f_iy_mst_whole <- "../X102_kikin_master_for_anal/ndb_master_creation/appendix/dfmeta_iy_20231122_150053_929635.xlsx"
df_iy <- readxl::read_excel(f_iy_mst_whole)
# df_iy <- read.xlsx(f_iy_mst_whole)
```

```{r}
df_ici <- df_iy %>% 
  filter(str_detect(c4, "キイトルーダ|オプジーボ|テセントリク|イミフィンジ|バベンチオ|ヤーボイ")) %>% 
  mutate(cod = as.character(c2))
d_in <- "../X102_kikin_master_for_anal/ndb_master_creation/output_iy/"
f_json <- list.files(d_in, full.names = T)
df_fs <- data.frame(f= f_json) %>% 
  mutate(cod = f %>% 
           str_replace_all(d_in, "") %>% 
           str_replace_all("iycode_", "") %>% 
           str_extract_all("^[0-9]*")) %>%
  filter(cod %in% as.character(df_ici$cod))



# %>% 
#   as.data.frame()
```

```{r}
df_whole <- data.frame()
for(i in 1:nrow(df_fs)){
  f_i <- df_fs$f[[i]]

  l_i <- read_json(f_i)  
  df_i <- as.data.frame(do.call(rbind, l_i$dt)) %>% 
    mutate(dt=rownames(.),
           f = f_i)
  # %>% 
  #   mutate(f = as.character(f))
  df_whole <- bind_rows(df_whole, df_i)
}


df_whole$dt %>% class()
# df_test <- 

# df_i %>% str()

df_whole <- df_whole %>% 
    mutate(cod = f %>% 
            unlist() %>% 
           str_replace(d_in, "") %>% 
           str_replace("iycode_", "") %>% 
           str_extract("^[0-9]*"))   %>% 
   left_join(df_ici, by="cod")
# df_i %>% str()
# df_whole$cod %>% class()


```

```{r}
df_whole %>% 
  group_by(tag) %>% 
  summarise(n=n()) %>% 
  DT::datatable()


df_whole %>% 
  group_by(c4) %>% 
  summarise(n=n()) %>% 
  DT::datatable()
  

df_vis <- df_whole %>% 
  filter(tag == "ws") %>% 
  mutate(drugname = c4 %>% 
           str_split_i("ｍｇ　", 1) %>% 
           str_replace("点滴静注", " ") %>% 
           str_replace("液", "") %>% 
           stringi::stri_trans_nfkc(),
         dt=dt %>% lubridate::ymd(),
         point = as.numeric(point)
           ) %>% 
  select(drugname, everything())

df_vis %>% 
  group_by(drugname) %>% 
  summarise(n=n())


```

```{r}
windowsFonts()
```


```{r}
require(ggpubr)
require(extrafont)
require(officer)
require(ggrepel)
loadfonts(device = "win", quiet = T)

df_vis_smr <- df_vis %>% 
  group_by(drugname) %>% 
  mutate(min_dt = min(dt)) %>% 
  filter(min_dt == dt)


p_ici2 <- ggplot()+
  theme_pubr(legend = "right", base_family = "Times New Roman")+
  geom_line(data = df_vis,
             aes(x=dt, y = point, color=drugname))+
  xlab("years")+ylab("yen")+labs(color="薬剤")
# +
#   ggplot2::scale_colour_brewer(palette = "Paired")
p_ici2

ggsave2_tri(p_ici2, wid = 26, hei = 18)
```


```{r}
p_ici3 <- ggplot()+
  theme_pubr(legend = "none", base_family = "Times New Roman")+
  geom_line(data = df_vis,
             aes(x=dt, y = point, color=drugname))+
  geom_text_repel(data = df_vis_smr,
                  aes(x=dt, y = point, color=drugname, label=drugname),
                  box.padding = 0.5, max.overlaps = Inf,
                  segment.color = "black",)+
  scale_color_manual(values = c(
    "#FF5733",  # オレンジ
    "#33FF57",  # ライムグリーン
    "#3366FF",  # ブルー
    "#FF33C2",  # ピンク
    "#FF5733",  # イエロー
    "#33FFFF",  # シアン
    "#FF3366",  # レッド
    "#33FFC2",  # グリーン
    "#FF33FF",  # マゼンタ
    "#33C2FF",  # スカイブルー
    "#FF9933",  # ゴールド
    "#33FF99",  # ティール
    "#9933FF"   # パープル
  ))+
  xlab("years")+ylab("yen")+labs(color="薬剤")
# +
#   ggplot2::scale_colour_brewer(palette = "Paired")
p_ici3

ggsave2_tri(p_ici3, wid = 26, hei = 18)

```


```{r}
df_tag <- df_iy %>% 
  filter(str_detect(c4, "キムリア")) %>% 
  mutate(cod = as.character(c2))

d_in <- "../X102_kikin_master_for_anal/ndb_master_creation/output_iy/"

f_json <- list.files(d_in, full.names = T)

df_fs <- data.frame(f= f_json) %>% 
  mutate(cod = f %>% 
           str_replace_all(d_in, "") %>% 
           str_replace_all("iycode_", "") %>% 
           str_extract_all("^[0-9]*")) %>%
  filter(cod %in% as.character(df_tag$cod))


df_whole <- data.frame()
for(i in 1:nrow(df_fs)){
  f_i <- df_fs$f[[i]]

  l_i <- read_json(f_i)  
  df_i <- as.data.frame(do.call(rbind, l_i$dt)) %>% 
    mutate(dt=rownames(.),
           f = f_i)
  # %>% 
  #   mutate(f = as.character(f))
  df_whole <- bind_rows(df_whole, df_i)
}


df_whole$dt %>% class()
# df_test <- 

# df_i %>% str()

df_whole <- df_whole %>% 
    mutate(cod = f %>% 
            unlist() %>% 
           str_replace(d_in, "") %>% 
           str_replace("iycode_", "") %>% 
           str_extract("^[0-9]*"))   %>% 
   left_join(df_ici, by="cod")
# df_i %>% str()
# df_whole$cod %>% class()


df_vis <- df_whole %>% 
  filter(tag == "ws") %>% 
  mutate(drugname = c4 %>% 
           str_split_i("ｍｇ　", 1) %>% 
           str_replace("点滴静注", " ") %>% 
           str_replace("液", "") %>% 
           stringi::stri_trans_nfkc(),
         dt=dt %>% lubridate::ymd(),
         point = as.numeric(point)
           ) %>% 
  select(drugname, everything()) %>% 
  dplyr::left_join(df_iy %>% mutate(c2 = as.character(c2)), by = c(cod="c2")) %>% 
  mutate(drugname = c4.y)

df_vis %>% 
  group_by(drugname) %>% 
  summarise(n=n())
```

```{r}
p_vis_k  <- ggplot()+
  theme_pubr(legend = "none", base_family = "Times New Roman")+
  geom_line(data = df_vis,
             aes(x=dt, y = point, color=drugname))+
  # geom_text_repel(data = df_vis_smr,
  #                 aes(x=dt, y = point, color=drugname, label=drugname),
  #                 box.padding = 0.5, max.overlaps = Inf,
  #                 segment.color = "black",)+
  # scale_color_manual(values = c(
  #   "#FF5733",  # オレンジ
  #   "#33FF57",  # ライムグリーン
  #   "#3366FF",  # ブルー
  #   "#FF33C2",  # ピンク
  #   "#FF5733",  # イエロー
  #   "#33FFFF",  # シアン
  #   "#FF3366",  # レッド
  #   "#33FFC2",  # グリーン
  #   "#FF33FF",  # マゼンタ
  #   "#33C2FF",  # スカイブルー
  #   "#FF9933",  # ゴールド
  #   "#33FF99",  # ティール
  #   "#9933FF"   # パープル
  # ))+
  xlab("years")+ylab("yen")+labs(color="薬剤")+
  coord_cartesian(expand = F, ylim = c(0, 35000000))

max(df_vis$point) - min(df_vis$point)

p_vis_k

ggsave2_tri(p_vis_k, wid = 18, hei = 14)
```


```{r}
sessionInfo()
```

