---
title: "S151_created_master_vis_iy"
author: "fk506.cni"
date: "2023-05-24"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
require(tidyverse)
require(openxlsx)
require(jsonlite)
require(officer)
require(ggpubr)
```


```{r}
outputdir <- "./figs/"
if(!dir.exists(outputdir)){
  dir.create(outputdir)
}

ggsave2_tri <- function(plot, wid = 9, hei=9){
  plot_name <- deparse(substitute(plot))
  
  #png
  file_name <- paste(outputdir,plot_name, ".png", sep = "",collapse = "")
  ggsave(filename = file_name,plot = plot,device = "png",width = wid, height = hei,dpi = 300,units = "cm")
  
  
  #pdf
  file_name <- paste(outputdir,plot_name, ".pdf", sep = "",collapse = "")
  # ggsave(filename = file_name,plot = plot,device = "pdf",width = wid, height = hei,dpi = 300,units = "cm")
  
  #pptx
  file_name <- paste(outputdir,plot_name, ".pptx", sep = "",collapse = "")
  plot_ed <- rvg::dml(ggobj = plot,width = wid, height = hei)
  
  doc <- read_pptx() %>%
    add_slide('Title and Content', 'Office Theme') %>%
    ph_with(value = "", location = ph_location_type(type = "title")) %>%
    ph_with(value = plot_ed, location = ph_location(type = "body",width = cm2inch(wid), height = cm2inch(hei),left = 2, top = 2))
  doc %>%
    print(target = file_name)
  
}



inch2cm <- function(x){
  return(x/0.39370)
}
cm2inch <- function(x){
  return(0.39370*x)
}

p2cm <- function(x){
  return(as.integer(0.008466666666666667 * x))
}

cm2p <- function(x){
  return(as.integer(118.11023622047244 *x))
}

sv2ggkm <- function(svfit){
  p <- ggsurvplot(fit = svfit, data = df,
                risk.table.title = "risk.table.title", risk.table.y.text.col = TRUE,
           risk.table.y.text = FALSE, fontsize = 5,
           risk.table = TRUE, tables.theme = theme_pubr(), ggtheme = theme_pubr())
  p_km <- p$plot
  p_tb <- p$table
  p2 <- cowplot::plot_grid(p_km, p_tb, ncol = 1,align = "v", rel_heights = c(3,1))
  grid::grid.draw(p2)
  return(p2)
}
```

```{r}
# f_mst_whole <- "../X102_kikin_master_for_anal/ndb_master_creation/appendix/dfmeta_iy_20230606_124628_792271.xlsx"
f_mst_whole <- "../X102_kikin_master_for_anal/ndb_master_creation/appendix/dfmeta_iy_20231122_150053_929635.xlsx"
# df_ <- read.xlsx(f_mst_whole)
df_ <- readxl::read_excel(f_mst_whole)


df_k <- df_ %>% 
  # filter(c90==10) %>% 
  filter(!str_detect(c4, "加算"))
```

```{r}

d_in <- "../X102_kikin_master_for_anal/ndb_master_creation/output_iy/"
f_json <- list.files(d_in, full.names = T)
df_fs <- data.frame(f= f_json) %>% 
  mutate(cod = f %>% 
           str_replace_all(d_in, "") %>% 
           str_replace_all("iycode_", "") %>% 
           str_extract_all("^[0-9]*")) %>%   
  filter(str_detect(cod, "641140136"))

# 
# df_fs %>% 
#   filter(str_detect(cod, "612320350"))
  
# %>% 
#   as.data.frame()
```
$nplcode
```{r}
df_whole <- data.frame()
# i <- 1000
nrow(df_fs)
for(i in 1:nrow(df_fs)){
  f_i <- df_fs$f[[i]]

  l_i <- read_json(f_i, encoding = "UTF-8")
  l_i$dt <- NULL
  df_i <- as.data.frame(l_i) %>% 
    mutate(f=f_i,
           nplcode = as.character(nplcode))
  
  l_i <- read_json(f_i, encoding = "UTF-8")
  df_i_dt <- as.data.frame(do.call(rbind, l_i$dt)) %>% 
    mutate(dt=rownames(.) %>% lubridate::ymd(),
           point=as.numeric(point),
           f = f_i) %>% 
    arrange(dt)  %>%
    # filter(tag == "ws") %>% 
    # 
    # group_by(f) %>% 
    # summarise(span = max(dt) - min(dt),
    #           sub_point = tail(point, n = 1) - head(point, n = 1),
    #           max_dt = max(dt),
    #           min_dt = min(dt),
    #           last_point=tail(point, n = 1),
    #           first_point = head(point, n = 1)) %>% 
    left_join(df_i, by="f")
  df_whole <- bind_rows(df_whole, df_i_dt)
}
# f_i
# 
# l_i
```


```{r}
time <- seq (1,7,1)
var1 <- c(3,5,7,2,3,2,8)
var2 <- c(2,4,18,16,12,3,2)
var2 <- c("a","4","a","16","a","4","16")
DF <- data.frame(time, var1, var2)

ggplot() + 
  geom_line(data=DF,
            aes(x=time, y = var1,colour=var2, group=1))

```


```{r}
require(ggrepel)
require(ggpubr)
require(extrafont)
require(officer)
loadfonts(device = "win", quiet = T)


df_vis <- df_whole %>% 
  mutate(dt = lubridate::ymd(dt),
         tagc = tag %>% unlist()) %>%
  as.data.frame()

# df_vis$tag %>% unlist()


p_one_drg <- ggplot()+
  theme_pubr(legend = "right",base_family = "Times New Roman")+
  # geom_line(data = df_vis,
  #           aes(x=dt, y= point))+
  geom_line(data = df_vis,
             mapping = aes(x=dt, y= point,color=tagc, group=1))+
  coord_cartesian(expand = F, ylim = c(91, 96))+
  xlab("years")+ylab("yen")
p_one_drg


ggsave2_tri(p_one_drg, wid = 15, hei=9)
```


```{r}
df_whole %>% 
  group_by(tag) %>% 
  summarise(n=n()) %>% 
  DT::datatable()


df_whole %>% 
  group_by(c4) %>% 
  summarise(n=n()) %>% 
  DT::datatable()
  

df_vis <- df_whole %>% 
  filter(tag == "ws") %>% 
  mutate(drugname = c4 %>% 
           str_split_i("ｍｇ　", 1) %>% 
           str_replace("点滴静注", " ") %>% 
           str_replace("液", "") %>% 
           stringi::stri_trans_nfkc(),
         dt=dt %>% lubridate::ymd(),
         point = as.numeric(point)
           ) %>% 
  select(drugname, everything())

df_vis %>% 
  group_by(drugname) %>% 
  summarise(n=n())


```

```{r}
windowsFonts()
```


```{r}
require(ggpubr)
require(extrafont)
require(officer)
loadfonts(device = "win", quiet = T)
p_ici <- ggplot()+
  theme_pubr(legend = "right")+
  geom_line(data = df_vis,
             aes(x=dt, y = point, color=drugname))
p_ici

ggsave2_tri(p_ici, wid = 26, hei = 18)
```


```{r}

```


```{r}
sessionInfo()
```

